
#' plot_sim
#'
#' Plot the result of genome simulation.
#'
#' @param data Simulation results data generated by the APAV tool.
#' @param chart_type A character string of chart type. It should be one of "errorbar", "jitter" and "ribbon".
#' @param data_type The type of data displayed. It should be "count" or "change".
#'
#' @param x_title The text for the x-axis title.
#' @param y_title The text for the y-axis title.
#' @param x_title_size The size of x-axis title.
#' @param y_title_size The size of y-axis title.
#' @param x_breaks A numeric vector of break values on the x-axis.
#' @param y_breaks A numeric vector of break values on the y-axis.
#' @param x_text_size The size of tick labels on x-axis.
#' @param y_text_size The size of tick labels on x-axis.
#'
#' @param legend_show Whether show the legend.
#' @param legend_side The position of legend.
#' @param legend_title The text for the legend title.
#' @param legend_title_size The size of legend title.
#' @param legend_text_size The size of legend item labels.
#'
#' @param errorbar_width A numeric vector giving the relative width of errorbar, ranging from 0 to 1.
#' @param errorbar_size The size of errorbar.
#' @param errorbar_color A string of color or a named vector of colors for errorbar.
#' @param errorbar_alpha The opacity of errorbar, ranging from 0 to 1.
#' @param errorbar_point_size The size of point representing the mean value.
#' @param errorbar_point_color A string of color or a named vector of colors for point representing the mean value.
#'
#' @param jitter_width A numeric vector giving the relative width of jittered points, ranging from 0 to 1.
#' @param jitter_size The size of jittered points.
#' @param jitter_color A string of color or a named vector of colors for jittered points.
#' @param jitter_alpha The opacity of jittered points, ranging from 0 to 1.
#' @param jitter_point_size The size of point representing the mean value.
#' @param jitter_point_color A string of color or a named vector of colors for point representing the mean value.
#'
#' @param path_size The size of path.
#' @param path_color A string of color or a named vector of colors for path.
#' @param ribbon_fill A string of color or a named vector of colors for ribbon.
#' @param ribbon_alpha The opacity of ribbon, ranging from 0 to 1.
#'
#' @import data.table
#' @import ggplot2
#'
#' @export
#'
plot_sim <- function(
    data,
    chart_type = "ribbon",
    data_type = "count",

    x_title = "Sample Number",
    y_title = NULL,
    x_title_size = NULL,
    y_title_size = NULL,
    x_breaks = NULL,
    y_breaks = NULL,
    x_text_size = NULL,
    y_text_size = NULL,

    legend_show = T,
    legend_side = "right",
    legend_title = NULL,
    legend_title_size = NULL,
    legend_text_size = NULL,

    errorbar_width = .8,
    errorbar_size = 1,
    errorbar_color = NULL,
    errorbar_alpha = .8,
    errorbar_point_size = 2,
    errorbar_point_color = NULL,

    jitter_width = .8,
    jitter_size = 1,
    jitter_color = NULL,
    jitter_alpha = .1,
    jitter_point_size = 2,
    jitter_point_color = NULL,

    path_size = 1,
    path_color = NULL,
    ribbon_fill = NULL,
    ribbon_alpha = 0.5
){

  chart_type <- match.arg(chart_type, choices = c("errorbar", "jitter", "ribbon"))
  data_type <- match.arg(data_type, choices = c("count", "change"))

  if(ncol(data) == 5 && all(colnames(data) == c("Round", "SampleN", "Core", "Pan", "Delta"))){

    if(data_type == "count"){
      s_data <- data[, 2:4]
    }else{
      s_data <- data[, c(2,5)]
    }
    p <- plot_s_sim(s_data,
                    chart_type,
                    errorbar_width,
                    errorbar_size,
                    errorbar_color,
                    errorbar_alpha,
                    errorbar_point_size,
                    errorbar_point_color,
                    jitter_width,
                    jitter_size,
                    jitter_color,
                    jitter_alpha,
                    jitter_point_size,
                    jitter_point_color,
                    path_size,
                    path_color,
                    ribbon_fill,
                    ribbon_alpha)

  }else if (ncol(data) == 6 && all(colnames(data) == c("Round", "SampleN", "Core", "Pan", "Delta", "Group"))){

    if(data_type == "count"){
      m_data <- data[, c(2:4, 6)]
      if(is.null(y_title))  y_title <- "Count"
    }else{
      m_data <- data[, c(2, 5, 6)]
      if(is.null(y_title))  y_title <- "Change value"
    }
    p <- plot_m_sim(m_data,
                    chart_type,
                    errorbar_width,
                    errorbar_size,
                    errorbar_color,
                    errorbar_alpha,
                    errorbar_point_size,
                    errorbar_point_color,
                    jitter_width,
                    jitter_size,
                    jitter_color,
                    jitter_alpha,
                    jitter_point_size,
                    jitter_point_color,
                    path_size,
                    path_color,
                    ribbon_fill,
                    ribbon_alpha)

    if(is.null(legend_title)) legend_title <- "Group"

  }else{
    stop("Format error")
  }

  if(!is.null(x_breaks)) p <- p + scale_x_continuous(breaks = x_breaks)
  if(!is.null(y_breaks)) p <- p + scale_y_continuous(breaks = y_breaks)

  p <- p +
    labs(
      x = x_title,
      y = y_title,
      color = legend_title,
      fill = legend_title,
      linetype = "",
      shape = "",
    ) + theme_classic()

  p <- p +
    theme(
      axis.title.x = element_text(size = x_title_size, color = "black", face = "bold"),
      axis.title.y = element_text(size = y_title_size, color = "black", face = "bold"),
      axis.text.x = element_text(size = x_text_size, color = "black", face = "bold"),
      axis.text.y = element_text(size = y_text_size, color = "black", face = "bold"),
      panel.grid = element_blank(),
      panel.background = element_blank()
    )

  p <- p + theme(
    legend.position = ifelse(legend_show, legend_side, "none"),
    legend.direction = ifelse(legend_side %in% c("top", "bottom"),
                              "horizontal", "vertical"),
    legend.title = element_text(size = legend_title_size, color = "black", face = "bold"),
    legend.text = element_text(size = legend_text_size, color = "black", face = "bold"),
    legend.key = element_rect(fill = NA, color = NA)
  )

  print(p)
}



plot_s_sim <- function(
    d,
    ct,

    errorbar_width,
    errorbar_size,
    errorbar_color,
    errorbar_alpha,
    errorbar_point_size,
    errorbar_point_color,

    jitter_width,
    jitter_size,
    jitter_color,
    jitter_alpha,
    jitter_point_size,
    jitter_point_color,

    path_size,
    path_color,
    ribbon_fill,
    ribbon_alpha

){

  d <- d[!is.na(d[2]),]
  dl <- data.table::melt(data.table::data.table(d), id.vars = "SampleN")
  value = SampleN = Length = variable = SD = sd = . = NULL
  d_stat <- dl[, .(Length = mean(value), SD = sd(value)), by = c("variable", "SampleN")]

  groups <- colnames(d)[-1]

  if(ct == "errorbar"){

    colors <- get_color(errorbar_color, groups)
    point_colors <- get_color(errorbar_point_color, groups)
    p <- ggplot(data = d_stat,
                aes(x = SampleN, y = Length, color = variable)) +
      geom_errorbar(aes(ymin = Length - SD, ymax = Length + SD),
                    width = errorbar_width,
                    linewidth = errorbar_size,
                    alpha =  errorbar_alpha) +
      geom_point(aes(fill = variable),
                 shape = 21,
                 size = errorbar_point_size) +
      scale_fill_manual(values = point_colors) +
      scale_color_manual(values = colors)

  } else if(ct == "jitter"){

    colors <- get_color(jitter_color, groups)
    point_colors <- get_color(jitter_point_color, groups)
    p <- ggplot() +
      geom_jitter(data = dl,
                  aes(x = SampleN, y = value, color = variable),
                  width = jitter_width,
                  height = 0,
                  size = jitter_size,
                  alpha = jitter_alpha) +
      geom_point(data = d_stat,
                 aes(x = SampleN, y = Length,
                     fill = variable, color = variable),
                 shape = 21,
                 size = jitter_point_size) +
      scale_fill_manual(values = point_colors) +
      scale_color_manual(values = colors)

  } else if (ct == "ribbon"){

    colors <- get_color(path_color, groups)
    fills <- get_color(ribbon_fill, groups)
    p <- ggplot()+
      geom_ribbon(data = d_stat,
                  aes(x = SampleN, y = Length,
                      ymin = Length - SD, ymax = Length + SD,
                      fill = variable),
                  alpha = ribbon_alpha) +
      geom_path(data = d_stat,
                aes(x = SampleN, y = Length, color = variable),
                linewidth = path_size) +
      scale_fill_manual(values = fills) +
      scale_color_manual(values = colors)

  }

  return(p)

}

plot_m_sim <- function(
    d,
    ct,

    errorbar_width,
    errorbar_size,
    errorbar_color,
    errorbar_alpha,
    errorbar_point_size,
    errorbar_point_color,

    jitter_width,
    jitter_size,
    jitter_color,
    jitter_alpha,
    jitter_point_size,
    jitter_point_color,

    path_size,
    path_color,
    ribbon_fill,
    ribbon_alpha

){

  d <- d[!is.na(d[2]),]
  dl <- data.table::melt(data.table::data.table(d), id.vars = c("SampleN", "Group"))
  value = SampleN = Length = variable = SD = Group = sd = . = NULL
  d_stat <- dl[, .(Length = mean(value), SD = sd(value)), by = c("variable", "SampleN", "Group")]

  groups <- unique(d$Group)

  if(ct == "errorbar"){

    colors <- get_color(errorbar_color, groups)
    point_colors <- get_color(errorbar_point_color, groups)
    p <- ggplot(data = d_stat,
                aes(x = SampleN, y = Length, color = Group)) +
      geom_errorbar(aes(ymin = Length - SD, ymax = Length + SD,
                        linetype = variable,
                        group = paste0(Group, variable)),
                    width = errorbar_width,
                    linewidth = errorbar_size,
                    alpha =  errorbar_alpha) +
      geom_point(aes(fill = Group, group = paste0(Group, variable)),
                 shape = 21,
                 size = errorbar_point_size) +
      scale_fill_manual(values = point_colors) +
      scale_color_manual(values = colors)

  } else if(ct == "jitter"){

    colors <- get_color(jitter_color, groups)
    point_colors <- get_color(jitter_point_color, groups)
    p <- ggplot() +
      geom_jitter(data = dl,
                  aes(x = SampleN, y = value,
                      color = Group, shape = variable,
                      group = paste0(Group, variable)),
                  width = jitter_width,
                  height = 0,
                  size = jitter_size,
                  alpha = jitter_alpha) +
      geom_point(data = d_stat,
                 aes(x = SampleN, y = Length, fill = Group,
                     color = Group, shape = variable,
                     group = paste0(Group, variable)),
                 size = jitter_point_size)+
      scale_fill_manual(values = point_colors) +
      scale_color_manual(values = colors)

  } else if (ct == "ribbon"){

    colors <- get_color(path_color, groups)
    fills <- get_color(ribbon_fill, groups)
    p <- ggplot(d_stat,
                aes(x = SampleN, y = Length)) +
      geom_ribbon(aes(ymin = Length - SD, ymax = Length + SD,
                      fill = Group, group = paste0(Group, variable)),
                  alpha = ribbon_alpha) +
      geom_path(aes(color = Group, group = paste0(Group, variable),
                    linetype = variable), linewidth = path_size) +
      scale_fill_manual(values = fills) +
      scale_color_manual(values = colors)

  }

  return(p)

}






